-- Create schema (optional, defaults to PUBLIC if omitted)

CREATE SCHEMA IF NOT EXISTS product_pricing;

-- Switch to schema
SET SCHEMA product_pricing;

-- Category table
CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(255) NOT NULL
);

-- Product table
CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         description VARCHAR(1000),
                         category_id BIGINT,
                         maximum_retail_price DECIMAL(19,2),
                         image_url VARCHAR(500),
                         CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id)
);
