spring.application.name=product-search
# Elasticsearch cluster (local or Testcontainers)
spring.elasticsearch.uris=http://localhost:9200

# Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
